### ISSUE TITLE
[New method suggestion] Augmentation-Augmented Variational Autoencoders

### ISSUE THREAD

**Issue by PeppeSaccardi** [vturrisi/solo-learn#110]
Ciao ragazzi!

I was wondering whether the new method [AAVAEs](https://arxiv.org/abs/2107.12329) proposed by William Falcon et al. can interest you and thus be implemented in your library or not. 

The authors of the paper claim and suggest that autoencoding is a viable third family of self-supervised learning approach in addition to contrastive and non-contrastive learning although their method failed to outperform or perform comparably to the existing families of self-supervised learning algorithms.

I really enjoyed the idea behind this method and I wanted to strongly suggest it to you!

**Comment by vturrisi** [comment]
Hey!

I've read the paper and it is indeed very interesting. We will add it to the pipeline, but if you wanna contribute please let us know and I can guide you through how to add new methods. We also plan on releasing "how to implement X" tutorials so the community can help! :)

**Comment by PeppeSaccardi** [comment]
Hi!
I would love to contribute! If you agree I can wait your official tutorials and then start to implement it.
Meanwhile thank you for considering this suggestion!
