### ISSUE TITLE
Implement AAVAE (https://arxiv.org/abs/2107.12329)

### ISSUE THREAD

**Issue by vturrisi** [vturrisi/solo-learn#111]

**Comment by PeppeSaccardi** [comment]
Hey I've just seen that you add the tutorials to implement a new method! Can I try to implement this method?

**Comment by vturrisi** [comment]
Hey @PeppeSaccardi, I copied the implementation from their original repo and ran some stuff on cifar, it was performing okayish, but now I'm not really sure how well.

I'll pull the main into that branch. If you wanna work on it, please feel free to :). I can guide you if you have any questions as well.

**Comment by vturrisi** [comment]
Managed to merge the main with aavae's branch and you should be able to run. After a couple of steps I'm getting an inf in the training loss, but now I won't be able to check if my parameters are messed up or what might be the issue.

**Comment by PeppeSaccardi** [comment]
Oh thank you! I will start looking at your code then, and in case I find something that I can contribute to I will let you know :+1:
