### ISSUE TITLE
About the category list of ImageNet-100 subset

### ISSUE THREAD

**Issue by Hiroki29** [vturrisi/solo-learn#116]
Hi @vturrisi, thanks for your great work and also sharing the code. 
Was the ImageNet-100 Checkpoint you posted trained on a subset of the following?

https://github.com/HobbitLong/CMC/blob/master/imagenet100.txt

If not, please give us a list of them.

**Comment by vturrisi** [comment]
Hey, thanks!

Yes, we used the same subset.

**Comment by Hiroki29** [comment]
I understand. Thanks a lot！
