### ISSUE TITLE
How to use these well trained model

### ISSUE THREAD

**Issue by fdszy** [vturrisi/solo-learn#123]
I appreciate your work, but I have some small questions.
The well-trained model you gave on the homepage is the encoder or encoder plus Linear?
How should I use these models?

**Comment by DonkeyShot21** [comment]
Hi. the checkpoints that we uploaded are just a copy of the model at the end of the training, so they contain all the parameters that are needed to resume training (i.e. the encoder, the projector and/or predictor, and the classifier). Note that the linear classifier contained in the checkpoints is trained online with the encoder. If you want to train the classifier offline, we have plenty of bash scripts for doing that in [here](https://github.com/vturrisi/solo-learn/tree/main/bash_files/linear).

The checkpoints can be loaded using PyTorch or even just tested using PyTorch Lightning. Here are some useful resources:
- [loading models with PyTorch](https://pytorch.org/tutorials/beginner/saving_loading_models.html)
- [loading models with PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/latest/common/weights_loading.html)

Note: if you are loading the weights manually, you can find the parameter groups of the model under the key `state_dict`.

**Comment by vturrisi** [comment]
Just to complement @DonkeyShot21, if you can check part of our code in `main_linear.py` that loads the encoder part:
https://github.com/vturrisi/solo-learn/blob/7abc7feb6120b02bb5a9ef372a474308f4a1b1c8/main_linear.py#L27-L51

**Comment by vturrisi** [comment]
I'll close, but if you have any questions, feel free to reopen the issue. Thanks for trying solo-learn :)
