### ISSUE TITLE
How to continue the training?

### ISSUE THREAD

**Issue by ludysama** [vturrisi/solo-learn#124]
my training process crashed for power problem, now I need to continue the training... 
But I don't know how to do it for it is the first time I use the pytorch-lightning

Thank you for help

**Comment by DonkeyShot21** [comment]
Hi, you can just launch the same command but adding `--resume_from_checkpoint="path/to/checkpoint"`. You should find your checkpoint in `trained_models/method/run_id`. The `run_id` is a unique identifier for your run that can be found on wandb in the info section of your run.

**Comment by ludysama** [comment]
It really worked, thank you very much. 

This library is really easy to use. 
Nice work. \(^o^)/~
