### ISSUE TITLE
A bug that occurs while using more than 2 num_crops and DALI

### ISSUE THREAD

**Issue by ludysama** [vturrisi/solo-learn#125]
I'm trying to train an old method 'Rotation Prediction' by the library which needs 4 crops of images, and then find a bug

in solo.methods.dali , around line 219

the origin code is 
    output_map = ["large1", "large2", "label"]

In fact, following codes is correct:
    output_map = []
    for i in range(self.num_crops):
        output_map.append(f"large{i+1}")
    output_map.append('label')

**Comment by vturrisi** [comment]
hey @ludysama, thanks for noticing this. Indeed we hardcoded this part for only 2-crops, which is indeed a problem since all the rest supports more than 2. Can you confirm that this fix works?

**Comment by ludysama** [comment]
I follow the codes step by step, and after rewrited this line, the algorithm can work well for the rotpred method

but I haven't try other methods now, maybe it will produce new bugs
