### ISSUE TITLE
Some problems when using the well trained model

### ISSUE THREAD

**Issue by fdszy** [vturrisi/solo-learn#127]
Hello!

Thank you for your previous answer.
However some errors occurred when i load the well trained simsiam model for cifar10:
_ModuleNotFoundError: No module named 'solo.methods'_
and moco for cifar100:
_RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory_

When I use simclr, byol, moco for cifar10, there is no such problem.

**Comment by DonkeyShot21** [comment]
Can you post a brief code snippet to reproduce the problem?

**Comment by fdszy** [comment]
`import torch
import torchvision
from torchvision import datasets
from tqdm import tqdm
from pl_bolts.models.self_supervised import SimCLR,BYOL
import torch.nn as nn
from sklearn.metrics import accuracy_score
import numpy as np
np.set_printoptions(threshold=np.inf)
torch.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, profile=None)
class linear(nn.Module):
    def __init__(self,n_features,n_classes):
        super(linear,self).__init__()
        self.model = nn.Linear(n_features,n_classes)

    def forward(self,x):
        return self.model(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = torchvision.models.resnet18()
model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=2, bias=False)
model.maxpool = nn.Identity()
model.fc = nn.Identity()
state = torch.load('simsiam_cifar10.ckpt',map_location=torch.device('cpu'))["state_dict"]


for k in list(state.keys()):
     if "encoder" in k:
         state[k.replace("encoder.", "")] = state[k]
     del state[k]
model.load_state_dict(state, strict=False)

model = model.to(device)
train_dataset = datasets.CIFAR10(root='./cifar10_dataset',train=True,transform=torchvision.transforms.ToTensor(),download=True)
test_dataset = datasets.CIFAR10(root='./cifar10_dataset',train=False,transform=torchvision.transforms.ToTensor(),download=True)

linear_model = linear(model.inplanes,10).to(device)

train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=128,
        shuffle=True,

        drop_last=True,
    )

test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=True,

        drop_last=True,
    )
optimizer = torch.optim.Adam(linear_model.parameters(), lr=3e-4)
criterion = torch.nn.CrossEntropyLoss()

for i in range(100):
    print(i)
    accuracy_epoch = 0
    loss_epoch = 0

    accuracy_sample = []
    total_sample = []
    for step, (x,y) in enumerate(tqdm(train_loader)):

        model.eval()
        x = x.cuda()
        y = y.cuda()
        r = model(x)

        output = linear_model(r)

        loss = criterion(output, y)
        predicted = output.argmax(1)
        predicted = predicted.cpu().numpy()
        predicted = list(predicted)
        accuracy_sample.extend(predicted)
        y = y.cpu().numpy()
        y = list(y)
        total_sample.extend(y)
        loss.backward()
        optimizer.step()

        loss_epoch += loss.item()

    print(accuracy_score(total_sample,accuracy_sample))
    print(loss_epoch/len(train_loader))
`
and it cause:
`Traceback (most recent call last):
  File "simsiam_cifar10.py", line 24, in <module>
    state = torch.load('simsiam_cifar10.ckpt')["state_dict"]
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'solo.methods'`

**Comment by fdszy** [comment]
```python
import torch
import torchvision
from torchvision import datasets
from tqdm import tqdm
from pl_bolts.models.self_supervised import SimCLR,BYOL
import torch.nn as nn
from sklearn.metrics import accuracy_score
import numpy as np
np.set_printoptions(threshold=np.inf)
torch.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, profile=None)
class linear(nn.Module):
    def __init__(self,n_features,n_classes):
        super(linear,self).__init__()
        self.model = nn.Linear(n_features,n_classes)

    def forward(self,x):
        return self.model(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = torchvision.models.resnet18()
model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=2, bias=False)
model.maxpool = nn.Identity()
model.fc = nn.Identity()
state = torch.load('simsiam_cifar10.ckpt',map_location=torch.device('cpu'))["state_dict"]


for k in list(state.keys()):
     if "encoder" in k:
         state[k.replace("encoder.", "")] = state[k]
     del state[k]
model.load_state_dict(state, strict=False)

model = model.to(device)
train_dataset = datasets.CIFAR10(root='./cifar10_dataset',train=True,transform=torchvision.transforms.ToTensor(),download=True)
test_dataset = datasets.CIFAR10(root='./cifar10_dataset',train=False,transform=torchvision.transforms.ToTensor(),download=True)

linear_model = linear(model.inplanes,10).to(device)

train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=128,
        shuffle=True,

        drop_last=True,
    )

test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=128,
        shuffle=True,

        drop_last=True,
    )
optimizer = torch.optim.Adam(linear_model.parameters(), lr=3e-4)
criterion = torch.nn.CrossEntropyLoss()

for i in range(100):
    print(i)
    accuracy_epoch = 0
    loss_epoch = 0

    accuracy_sample = []
    total_sample = []
    for step, (x,y) in enumerate(tqdm(train_loader)):

        model.eval()
        x = x.cuda()
        y = y.cuda()
        r = model(x)

        output = linear_model(r)

        loss = criterion(output, y)
        predicted = output.argmax(1)
        predicted = predicted.cpu().numpy()
        predicted = list(predicted)
        accuracy_sample.extend(predicted)
        y = y.cpu().numpy()
        y = list(y)
        total_sample.extend(y)
        loss.backward()
        optimizer.step()

        loss_epoch += loss.item()

    print(accuracy_score(total_sample,accuracy_sample))
    print(loss_epoch/len(train_loader))


```

and it caused:

```python
Traceback (most recent call last):
  File "simsiam_cifar10.py", line 24, in <module>
    state = torch.load('simsiam_cifar10.ckpt')["state_dict"]
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/xinlei.he/.local/lib/python3.7/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'solo.methods'
```
Thanks a lot for your help.

**Comment by DonkeyShot21** [comment]
Sorry, but I can't reproduce the error. I ran the following:
``` 
>>> import torch
>>> state = torch.load('simsiam-cifar10-252e1tvw-ep=999.ckpt', map_location=torch.device('cpu'))["state_dict"]
>>> len(state.keys())
147
```

Are you sure that you have `solo` installed in your environment? You can run `pip list | grep solo` and check if it appears. If it doesn't, just install it like this (from the root folder of the repo):
```
pip3 install .[dali,umap]
```

BTW, you are importing SimCLR and BYOL from `pl_bolts.models.self_supervised`, not from `solo.methods`.

However, I actually suggest that you use our linear eval class, it is very easy to use. As said we have precompiled scripts for this (e.g. for [simsiam](https://github.com/vturrisi/solo-learn/blob/main/bash_files/linear/simsiam_linear.sh)). You just need to change a few args to adapt to cifar. Something like this should work:
```
python3 ../../main_linear.py \
    --dataset cifar10 \
    --encoder resnet18 \
    --data_dir /datasets \
    --max_epochs 100 \
    --gpus 0 \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 30.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 10 \
    --name simsiam-cifar10-linear-eval \
    --pretrained_feature_extractor PATH \
    --project solo-learn \
    --entity your-entity \
    --wandb
```

**Comment by fdszy** [comment]
Ok, Thanks a lot. I will try your precompiled scripts.

**Comment by saifhassan** [comment]
> Sorry, but I can't reproduce the error. I ran the following:
> 
> ```
> >>> import torch
> >>> state = torch.load('simsiam-cifar10-252e1tvw-ep=999.ckpt', map_location=torch.device('cpu'))["state_dict"]
> >>> len(state.keys())
> 147
> ```
> 
> Are you sure that you have `solo` installed in your environment? You can run `pip list | grep solo` and check if it appears. If it doesn't, just install it like this (from the root folder of the repo):
> 
> ```
> pip3 install .[dali,umap]
> ```
> 
> BTW, you are importing SimCLR and BYOL from `pl_bolts.models.self_supervised`, not from `solo.methods`.
> 
> However, I actually suggest that you use our linear eval class, it is very easy to use. As said we have precompiled scripts for this (e.g. for [simsiam](https://github.com/vturrisi/solo-learn/blob/main/bash_files/linear/simsiam_linear.sh)). You just need to change a few args to adapt to cifar. Something like this should work:
> 
> ```
> python3 ../../main_linear.py \
>     --dataset cifar10 \
>     --encoder resnet18 \
>     --data_dir /datasets \
>     --max_epochs 100 \
>     --gpus 0 \
>     --precision 16 \
>     --optimizer sgd \
>     --scheduler step \
>     --lr 30.0 \
>     --lr_decay_steps 60 80 \
>     --weight_decay 0 \
>     --batch_size 256 \
>     --num_workers 10 \
>     --name simsiam-cifar10-linear-eval \
>     --pretrained_feature_extractor PATH \
>     --project solo-learn \
>     --entity your-entity \
>     --wandb
> ```

Hey @DonkeyShot21 @fdszy @turian @Froskekongen @Borda,

I have tried running this file but causing following error, can anyone of you please guide me?
```
usage: main_linear.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE]
                      [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH]
                      [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--experimental-rerun EXPERIMENTAL_RERUN]
                      [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                      [overrides [overrides ...]]
main_linear.py: error: unrecognized arguments: --dataset --backbone resnet18 --data_dir ./ --max_epochs 100 --gpus 0 --sync_batchnorm --precision 16 --optimizer sgd --scheduler step --lr 0.1 --lr_decay_steps 60 80 --weight_decay 0 --batch_size 128 --num_workers 4 --name general-linear-eval --pretrained_feature_extractor cifar10/byol-cifar10.ckpt --project self-supervised --wandb

```
Thanks in advance
