### ISSUE TITLE
Handling of custom datasets

### ISSUE THREAD

**Issue by rinku5324** [vturrisi/solo-learn#129]
Can I use this code base to run the methods over multispectral images. 
i have to take care of transformations differently.
Data will be .tif file rather .png 
Backbones will be slightly different as now the first conv layer will have n in_channels compared to 3 in plain images

**Comment by vturrisi** [comment]
I'm closing this, but feel free to reopen if you have any new questions

**Comment by ankitpatnala** [comment]
Hi ! I have one issue while using transformation for custom data
Though, i am able to run my model but it is taking lot of time for 1 epoch. I am not sure whether it is due to dataloader or is it supposed to be that slow in general (20 mins for 1 epoch)
let me carry you through my dataset and transformation
![image](https://user-images.githubusercontent.com/26856470/131986897-c52a2062-7d55-419a-af93-ea68c885ebab.png)
i am reading a raster files using rasterio which returns  (4,64,64) array of type float32

Below, i am sharing my transformation pipeline
![image](https://user-images.githubusercontent.com/26856470/131987226-a5ee7c22-0830-498b-8ac5-471006eeccd2.png)
![image](https://user-images.githubusercontent.com/26856470/131987257-fd78805d-c73e-45ef-b934-97ac4c91e575.png)
i have to do some transformations for rgb channels specifically like color jittering, grayscale

I see in your readme that it took  4m 55s for a resnet18 model to run 1 epoch of  imagenet data. I assume you use all arguments same what was mentioned in bash-scripts i.e batch_size 128 * (2 GPUs). It has 100,000 images (900,000 training and 10,000 validation).

I took the  batch_size 128*(4 GPUs) for a resnet 50 model. Total number of rasters i have is 27000( 21000 training and 6000 validation). i am running Barlow_twins model. i also changed num_workers to "1"

Do you think it is normal or am i having a performance bottle neck ? 
Do you have any suggestion to boost  my training ?

**Comment by vturrisi** [comment]
Hey,

Next time, please reopen the issue, it's easier for us to see.

I'll try to go through all the points you made.
Regarding rasterio, I've never used it, so I can't know how fast/slow it is. I would suggest that you just create a dummy dataloader (just return random noise in the shape that you need) so you can see how long each epoch takes without relying on rasterio. Of course, if your bottleneck is this, unfortunately, there's not much we could do.

Your transformation pipeline seems fairly complicated, so I assume there's a large bottleneck there. Maybe you could also try to disable it temporarily as well.

Doing these 2 steps, you can roughly estimate how long it takes to do data loading and how long it takes to do your augmentations.

About the model, the 5 minutes is for a resnet18 on imagenet100, so it's 10 times smaller than the full imagenet. It is still larger than your dataset, though.

Regarding the number of workers, setting it to 1 is a huge bottleneck. Usually the more the better (up to some point), I would suggest 4-5 or more, depends on your gpu, CPU and SSD. Also note that this is per gpu, so if you have two gpus and 5 workers, it's actually 10 workers in total.

As you can see in our experiments, we have a 56% improvement for Barlow when using dali, which is much better optimized. So I would assume most of your bottleneck is on the data loading side, which you can confirm with the experiments I suggested.

Let me know if I can help in anything else!

**Comment by vturrisi** [comment]
Hey,

I'll try to go through all the points you made.
Regarding rasterio, I've never used it, so I can't know how fast/slow it is. I would suggest that you just create a dummy dataloader (just return random noise in the shape that you need) so you can see how long each epoch takes without relying on rasterio. Of course, if your bottleneck is this, unfortunately, there's not much we could do.

Your transformation pipeline seems fairly complicated, so I assume there's a large bottleneck there. Maybe you could also try to disable it temporarily as well.

Doing these 2 steps, you can roughly estimate how long it takes to do data loading and how long it takes to do your augmentations.

About the model, the 5 minutes is for a resnet18 on imagenet100, so it's 10 times smaller than the full imagenet. It is still larger than your dataset, though.

Regarding the number of workers, setting it to 1 is a huge bottleneck. Usually the more the better (up to some point), I would suggest 4-5 or more, depends on your gpu, CPU and SSD. Also note that this is per gpu, so if you have two gpus and 5 workers, it's actually 10 workers in total.

As you can see in our experiments, we have a 56% improvement for Barlow when using dali, which is much better optimized. So I would assume most of your bottleneck is on the data loading side, which you can confirm with the experiments I suggested.

Let me know if I can help in anything else!

**Comment by ankitpatnala** [comment]
Hey,

Thanks for the reply. I will implement your suggestions and get back to you.
One doubt regarding num_workers.  The more i use, of course it also becomes a bottleneck and it doesn't even start . As i use 4 GPUs , shall i go for 2 per gpu ?

**Comment by vturrisi** [comment]
It really depends on your hardware. I think it's more a matter of testing. Generally, after some number of works, you start to be bottlenecked by the GPU (so you don't see any speedups in training time) and then it will start to get slower and slower. Also, in a 4 GPU machine, I assume CPU/ram isn't going to be a problem, so you can probably keep the same number of workers.

**Comment by ankitpatnala** [comment]
So, i checked the time for data without transformation, it takes around 3 min / epoch with 4 GPUS  and ( 1 workers per GPU). It is such a huge difference

**Comment by vturrisi** [comment]
I see. Also, the part where you convert to numpy seems a bit strange to me, is it needed?

**Comment by ankitpatnala** [comment]
Sorry, i shared the snippet of old code. I had removed it.
![image](https://user-images.githubusercontent.com/26856470/132038815-075e3e78-3e33-441f-a0ef-183fc2b4978e.png)
i had also changed the raster_loader to get torch float32
![image](https://user-images.githubusercontent.com/26856470/132038886-4215ca9e-50a1-435d-953a-d19c47dd2406.png)

**Comment by vturrisi** [comment]
ok! and if you don't do your transformations, you go from 20min per epoch to 3?

**Comment by ankitpatnala** [comment]
yes, exactly.

**Comment by ankitpatnala** [comment]
How are transformation functions on torch Tensor compared to PIL image ? Can there be performance bottleneck over there ?

**Comment by ankitpatnala** [comment]
> ok! and if you don't do your transformations, you go from 20min per epoch to 3?

now i am using resnet 18 for testing, so it changed from 12 min per epoch to 3 but still a lot

**Comment by vturrisi** [comment]
I know that recently torchvision implemented some stuff to do transformations directly on tensors/gpu (I can try to find it later, but I think it was version 0.8 or 0.9). I tried this myself (not pushed too much) and I saw zero difference in performance.
I would suggest that you try adding one transformation at a time (there might be just one or a couple of transformations that are really heavy) for extra debugging. Apart from that, you could try [kornia](https://github.com/kornia/kornia) or other libraries, but I won't be of much help.

Nvidia's DALI will for sure boost your performance, but it's more complicated to implement the transformations, but you might wanna take a look at that if it can support the type of data that you need to load. The transformations themselves are more straightforward.

**Comment by ankitpatnala** [comment]
Thanks for the suggestion. I will try doing each transformations separately and see. 
I have already tried kornia. It was of not that great help. 
Regarding nvidia dali, i am not really sure do they have for custom data. I guess they mostly have for images, audios and videos not fr multi-spectral.

**Comment by vturrisi** [comment]
Yeah, I think it's not easily supported, but might be worth checking anyway.
I'm closing this issue, but if you wanna ask any questions/update if you find a good solution for you problem, let me know.
thanks!

**Comment by ankitpatnala** [comment]
Hi, 
The bottleneck is Randomresizeandcropping. As soon as i removed the transformation, the speed is normal and fast. The bicubic interpolation is something which is taking lot of time. I didn't find any alternative solution to it but will try to search for something to tackle that.
