### ISSUE TITLE
Configuration for BYOL - Imagenet-1000

### ISSUE THREAD

**Issue by priyamdey** [vturrisi/solo-learn#131]
Hello!

For the BYOL run on Imagenet-1000, I could not find any bash file for the same in the 'main' branch. Can you please provide the configuration for this setting? I see the results table filled up for BYOL on Imagenet-1000 in the readme.

Thanks a lot!

**Comment by DonkeyShot21** [comment]
Hi, you are right, we missed that. Here it is:
```
python3 ../../../main_pretrain.py \
    --dataset imagenet \
    --encoder resnet50 \
    --data_dir /datasets \
    --train_dir ILSVRC2012/train \
    --val_dir ILSVRC2012/val \
    --max_epochs 100 \
    --gpus 0,1 \
    --distributed_backend ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --eta_lars 0.001 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.45 \
    --accumulate_grad_batches 16 \
    --classifier_lr 0.2 \
    --weight_decay 1e-6 \
    --batch_size 128 \
    --num_workers 8 \
    --dali \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --asymmetric_augmentations \
    --name byol-resnet50-imagenet-100epochs \
    --entity unitn-mhug \
    --project solo-learn \
    --wandb \
    --method byol \
    --output_dim 256 \
    --proj_hidden_dim 4096 \
    --pred_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier
```
If you have problems with memory you can decrease the number of workers or remove the momentum classifier.

I will also add it to the bash files folder. Thanks for spotting this.

**Comment by priyamdey** [comment]
Thanks for sharing the configurations. I had one more query regarding the dali dataloader. I'm new to DALI so need some help on this. Where exactly is dali dataloader being used by the lightning Trainer? In the ```main_pretrain.py``` ([here](https://github.com/vturrisi/solo-learn/blob/4c195ca066a24ad6569f713f65137c8e1117a839/main_pretrain.py#L163)), there is no dali-loader being used.

**Comment by DonkeyShot21** [comment]
About DALI, you can check the code [here](https://github.com/vturrisi/solo-learn/blob/main/solo/methods/dali.py) and [here](https://github.com/vturrisi/solo-learn/blob/main/solo/utils/dali_dataloader.py)
