### ISSUE TITLE
Configuration for linear eval of BYOL on cifar-10/100

### ISSUE THREAD

**Issue by priyamdey** [vturrisi/solo-learn#133]
Hi!

I had tried a slightly modified version of BYOL on cifar-10/100. The results of additional class-classifier used in pretraining are 1% (cifar-10) and 6% (cifar-100) better than the classifier trained  with the final backbone during linear evaluation. This might be due to the fact that we used the IN-100 configuration of BYOL for linear evaluation. The cifar-10/100 configuration for linear evaluation is not provided. It would be very helpful if you can share the respective configurations for cifar.

Thanks!

**Comment by DonkeyShot21** [comment]
Hi! We haven't experimented much with offline linear eval on CIFAR. The results with online eval are already quite good. Maybe we will do this in the future but not for now. 

To improve the performance of online eval you might want to tune the hyperparameters, maybe add some augmentations. Let us know if you manage to get good results.
