### ISSUE TITLE
Loss curves for VICReg

### ISSUE THREAD

**Issue by anuj-sharma-19** [vturrisi/solo-learn#138]
Hi,

Thank you very much for the excellent work on bringing all the different self supervised models at one place, and high code quality.

I am currently working on the VICReg loss, and was wondering if you had any loss curves for invariance/ covariance/ variance losses with you, and if you could please share it? It would be really helpful for me to understand the behaviour of these losses.

Looking forward to your help.

Thank You.

Best Regards,
Anuj

**Comment by vturrisi** [comment]
Hey,

Thanks for the comments!

We didn't decouple the losses when plotting, but you could do this by modifying this: https://github.com/vturrisi/solo-learn/blob/afd26ef6abc99bc28bd6836fa82c07593d7b692f/solo/losses/vicreg.py#L63-L89
Making it return all the individual pieces, logging them and then do the weighted sum.

Here's the plot of the combined loss for Imagenet-100 with 400 epochs.

![image](https://user-images.githubusercontent.com/34046216/133464097-6aad9810-bc12-4f3d-98d9-34aca58398c6.png)

Hope it helps! If you need anything let me know.

**Comment by anuj-sharma-19** [comment]
Hi,

Thanks a lot for sharing the loss curve above, its quite helpful to see the overall trend and the loss magnitudes as well !!

Actually, I was applying the VICReg to custom dataset, and could not train on ImageNet yet, so was thinking if you had them for each of the individual losses. I will do the logging for each of them.

Thanks again !!

Best Regards,
Anuj

**Comment by vturrisi** [comment]
Unfortunately, I just have the aggregated loss. We might try to think of a way to return the individual parts of the loss just for logging in a concise way. If you run any of the custom datasets and wanna share the individual losses, fell free to reopen the issue :)
