### ISSUE TITLE
Linear Model missing "patch_size" parameter

### ISSUE THREAD

**Issue by invisprints** [vturrisi/solo-learn#139]
When I run the following script

```sh
python main_linear.py \
    --dataset cifar10 \
    --encoder resnet18 \
    --data_dir ./datasets \
    --max_epochs 100 \
    --gpus 0 \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 1.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 5 \
    --name simclr-cifar10-linear-eval \
    --pretrained_feature_extractor  EXTRATOR_PATH \
    --project selfsupervised  \
    --wandb
```
 The program raise Error: 'Namespace' object has no attribute 'patch_size'

It seems Linear Model missing some required parameters

**Comment by DonkeyShot21** [comment]
Hi, thanks for finding this bug. Probably something went wrong when we added ViT. @vturrisi is refactoring the backbones so a fix for this will come soon. For now, you can just pass a random patch size, it will not be used, since you selected a resnet backbone.

**Comment by invisprints** [comment]
Thanks. By the way, I also find a bug in https://github.com/vturrisi/solo-learn/blob/afd26ef6abc99bc28bd6836fa82c07593d7b692f/main_linear.py#L34
It should be `if args.backbone_args['cifar']:`

**Comment by vturrisi** [comment]
Thanks for letting us know. I'm in the process of replacing our backbones with `timm`, so this should be fixed in a couple of hours at most.

**Comment by vturrisi** [comment]
hey @invisprints, can you check if the branch `new/backbones` fixes it for you?
I did some tests and it should be working.

**Comment by vturrisi** [comment]
Quick update: the new version should fix what you are experiencing, but let us know!

**Comment by invisprints** [comment]
Cool, thank you for your hard work!
