### ISSUE TITLE
train on custom dataset

### ISSUE THREAD

**Issue by mbenami** [vturrisi/solo-learn#161]
Hi I try to train on a custom dataset (~150k images )
with `bash_files/pretrain/custom/byol.sh`
I change 
```
--train_dir path_to_dir_with_all_images
```  
and add the `--no_labels` flag 
I got failed for CUDA out of memory 
and on the train prints I see
```
1 | classifier         | Linear                | 306 M 
```
debugging the code and I see inline 
https://github.com/vturrisi/solo-learn/blob/09f5f895330822517e484258e22be1add0900122/solo/methods/base.py#L235

that `num_classes = #num_of_images` (~150k)
is that what supposed to be? 
in case we have flag `no_labels` don't we want to remove the classifier layer? 
thanks for the help

**Comment by vturrisi** [comment]
Hey @mbenami, sorry about the long delay. Can you try to reproduce the error again to see if it's persistent? I checked our code and `--no_labels `should return only `-1` as labels. If the issue is still there, can you share your script?

**Comment by mbenami** [comment]
Hi @vturrisi 
(sorry for the late replay got to work on other matters )
when I run with debugging I got `num_classes` as the number of images in my images folder 
all I need to do is to add my dataset to `_N_CLASSES_PER_DATASET` 
https://github.com/vturrisi/solo-learn/blob/6f19d5dc38fb6521e7fdd6aed5ac4a30ef8f3bd8/solo/args/pretrain.py#L17

`    "custom": 1` and no more memory issue
