### ISSUE TITLE
Pass data augmentation hyperparameters as arguments

### ISSUE THREAD

**Issue by koushik-n** [vturrisi/solo-learn#162]
Is it possible to add these augmentation hyperparameters ( color_jitter_prob: float = 0.8, gray_scale_prob: float = 0.8, horizontal_flip_prob: float = 0.5) as arguments that can be passed to code similar to other parameters (gaussian_prob and solarization_prob)?

**Comment by vturrisi** [comment]
Hey!
This was actually supposed to be the case in our last commit, but seems like we missed this. I'll add it soon enough and also fix the default value for gray_scale_prob.

**Comment by koushik-n** [comment]
Thanks!. Please also modify the bash file for custom data with these new arguments if possible!
