### ISSUE TITLE
Problem about using repo

### ISSUE THREAD

**Issue by MrChenFeng** [vturrisi/solo-learn#168]
I tried to install the repo and the provided scripts however met pkg dependencies error. Also tried conda new env with the given requirements file still failed. Any idea about fixing this?

Thanks so much!
Best.

**Comment by vturrisi** [comment]
Hey,
Can you provide the error messages that you got? One known issue to us is that our `setup` is not correctly installing DALI, which we still haven't fixed. You can install it following `https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html`
