### ISSUE TITLE
wandb logging error

### ISSUE THREAD

**Issue by sooonwoo** [vturrisi/solo-learn#183]
It seems the wandb logging system is not working. 

![image](https://user-images.githubusercontent.com/32264161/140678855-ae71a704-a3da-4e86-9a51-34f445701d1a.png)

**Comment by vturrisi** [comment]
Hey, can you send the script that you are running?

**Comment by sooonwoo** [comment]
I used sh barlow.sh for cifar experiment

**Comment by vturrisi** [comment]
It logs to our entity. You need to either change the --entity parameter to either your id or to a group that you are part of or just remove it completely.

**Comment by sooonwoo** [comment]
Oh, Appreciate! The problem is resolved.
