### ISSUE TITLE
Wrong implementation for SupCon (SimCLR correct computation)

### ISSUE THREAD

**Issue by Hong753** [vturrisi/solo-learn#185]
Hi I just wanted to point out that your implementation for SupCon is wrong (supervised + SimCLR).

In the code "solo-learn/solo/losses/simclr.py" lines 71 and 109, 
you are dividing by using ".../pos_mask.sum(1)".
In this way, the division is done along the 0 axis which belongs to the batch size, while it should be done along axis 1.
Simply adding unsqueeze, i.e., ".../pos_mask.sum(1).unsqueeze(-1)" should fix the issue.

Note: the computation for SimCLR is correct since the sum is always 1 (without multiview, I didn't check when multiview is used)

**Comment by vturrisi** [comment]
Hey,
Thanks for letting us know. I'll take a better look in the next couple days and get back to you as soon as I can.

**Comment by Hong753** [comment]
I apologize. I realized I modified the line in my own experimentation with your code. Your implementation is correct.

**Comment by vturrisi** [comment]
Ok! no worries
