### ISSUE TITLE
GPU memory usage kept rising

### ISSUE THREAD

**Issue by NPU-Franklin** [vturrisi/solo-learn#186]
When I trained on my customed dataset, the GPU memory allocated kept rising, even if I try to use `torch.cuda.empty_cache()`, this problem remained. And after I lowered the batch_size, the program was still terminated on OOM error.
![image](https://user-images.githubusercontent.com/54883050/141256188-b0850170-a24e-4f17-a7f2-ef89dcb3fdcb.png)

**Comment by DonkeyShot21** [comment]
Hi! Thanks for using the repository. 

Are you using Dali?

**Comment by vturrisi** [comment]
Hey,

Are you using dali? It's normal for memory to increase, but it usually stabilizes after 30 epochs or so (for imagenet/imagenet100). If you are using dali, can you try without it and see if the issue still persists?

**Comment by NPU-Franklin** [comment]
No I am not. Here are some of the settings of my training.
```bash                                           
python ../../../main_pretrain.py \                                        
    --dataset custom \                                                    
    --encoder resnet18 \                                                  
    --data_dir customed \                  
    --train_dir customed \                                         
    --no_labels \                                                         
    --max_epochs 400 \                                                    
    --gpus 0,1,2,3 \                                                      
    --accelerator ddp \                                                   
    --sync_batchnorm \                                                    
    --precision 16 \                                                      
    --optimizer sgd \                                                     
    --lars \                                                              
    --grad_clip_lars \                                                    
    --eta_lars 0.02 \                                                     
    --exclude_bias_n_norm \                                               
    --scheduler warmup_cosine \                                           
    --lr 0.01 \                                                           
    --accumulate_grad_batches 1 \                                         
    --classifier_lr 0.1 \                                                 
    --weight_decay 1e-5 \                                                 
    --batch_size 128 \                                                    
    --num_workers 12 \                                                    
    --brightness 0.4 \                                                    
    --contrast 0.4 \                                                      
    --saturation 0.2 \                                                    
    --hue 0.1 \                                                           
    --color_jitter_prob 0.8 \                                             
    --horizontal_flip_prob 0.5 \                                          
    --gaussian_prob 1.0 0.1 \                                             
    --solarization_prob 0.0 0.2 \                                         
    --num_crops_per_aug 1 1 \                                             
    --name byol-400ep-TCGA \                                         
    --entity  \                                               
    --project solo-learn \                                                
    --wandb \                                                             
    --save_checkpoint \                                                   
    --method byol \                                                       
    --proj_output_dim 256 \                                               
    --proj_hidden_dim 4096 \                                              
    --pred_hidden_dim 8192 \                                              
    --base_tau_momentum 0.99 \                                            
    --final_tau_momentum 1.0 \                                            
    --checkpoint_frequency 50 \                                           
    --accelerator 'ddp'                                              
```

**Comment by DonkeyShot21** [comment]
Can you try to disable knn eval as well?

**Comment by NPU-Franklin** [comment]
OK, I will give it a shot.

**Comment by NPU-Franklin** [comment]
Thanks for your advice. By disabling knn eval, GPU memory usage has stopped climbing. I somehow missed that part when checking the algorithms described in `base.py`. Thanks again. 🙏

**Comment by vturrisi** [comment]
Good to know! We have been struggling with some internal leak (which we think is related to pytorch lightning in some way) in our knn evaluation. We will make it false by default so other users don't encounter this issue.

I'll close the issue, but feel free to open new ones!

**Comment by mbenami** [comment]
Hi had the same issue
adding the flag `--disable_knn_eval` solve also for me 

there is some inconsistency with the default parameters 
here:
https://github.com/vturrisi/solo-learn/blob/45c143dfac6e8a09258081b893726474dba04640/solo/methods/base.py#L308 
the parser has default `False` for `store_true` action 
but here: 
https://github.com/vturrisi/solo-learn/blob/45c143dfac6e8a09258081b893726474dba04640/solo/methods/base.py#L84 
the default for  `disable_knn_eval` is True

**Comment by vturrisi** [comment]
Hey, I'm going to fix the `knn_eval` stuff and leave it off as default. About `no_labels` we return -1 for all instances, which are then ignored in https://github.com/vturrisi/solo-learn/blob/45c143dfac6e8a09258081b893726474dba04640/solo/methods/base.py#L434 and https://github.com/vturrisi/solo-learn/blob/45c143dfac6e8a09258081b893726474dba04640/solo/methods/base.py#L688

**Comment by vturrisi** [comment]
KNN eval is now off by default (https://github.com/vturrisi/solo-learn/pull/190). You can turn it on with `--knn_eval`.
