### ISSUE TITLE
Weak and Strong Transformation

### ISSUE THREAD

**Issue by ankitpatnala** [vturrisi/solo-learn#187]
Hi ! I was wondering can we able to use weak/strong transformation. The one mentioned in ReSSL paper ?
I guess currently we use same transformation for both online and target network.
Please correct me if i am wrong.

**Comment by vturrisi** [comment]
Our augmentations are all customizable via the bash files. If you check the bash file for ReSSL (https://github.com/vturrisi/solo-learn/blob/main/bash_files/pretrain/imagenet-100/ressl.sh), specifically this part:
```
--brightness 0.4 0.0 \
--contrast 0.4 0.0 \
--saturation 0.4 0.0 \
--hue 0.1 0.0 \
--gaussian_prob 0.5 0.0 \
--solarization_prob 0.0 0.0 \
--num_crops_per_aug 1 1 \
```
You can see that the second augmentation has no brightness/contrast/saturation/hue strength nor gaussian and polarization probability. The script is somewhat old and we restructured part of the parameters. I think this can also work:
```
--brightness 0.4 \
--contrast 0.4 \
--saturation 0.4 \
--hue 0.1 \
--gaussian_prob 0.5 0.0 \
--solarization_prob 0.0 0.0 \
--color_jitter_prob 0.8 0.0 \
--num_crops_per_aug 1 1 \
```
