### ISSUE TITLE
Failed to launch sweep with multiple gpus (related to #188)

### ISSUE THREAD

**Issue by YugeTen** [vturrisi/solo-learn#192]
Are there any instructions for setting up runs across multiple gpus (single node)? 

To set up an example run using 2 gpus, I specified `gpus` as 2 in the sweep yaml file, however, when I launch with `CUDA_VISIBLE_DEVICES=0,1` the process hangs before the start of training.

**Comment by vturrisi** [comment]
Hey,
Just to clarify, are you using wandb sweep feature? Also, are you able to run the same script with 2 gpus without sweep?

**Comment by YugeTen** [comment]
Just checked and it hangs at the same place!

Probably doing something wrong on my end since I'm very new to this, but here's the command that I used:

```
CUDA_VISIBLE_DEVICES=0,1 python main_pretrain.py --gpus 0,1
```

**Comment by vturrisi** [comment]
Humm... I'm not really sure because I can run just fine with these settings. Can you do single-gpu training?

**Comment by YugeTen** [comment]
Apologies, I just tried it on a different cluster and it seems to work now. Thank you so much for the quick response!
