### ISSUE TITLE
Checkpointer

### ISSUE THREAD

**Issue by ankitpatnala** [vturrisi/solo-learn#193]
How does it work when the validation_loader is None. It doesn't save model checkpoints with the custom checkpointer callback ? i am using currently default checkpoint args of trainer but i am not really sure why the custom checkpoint callback not working ? Is it only for me or is it happening with you also ?
![image](https://user-images.githubusercontent.com/26856470/142849411-d83e5041-34f1-4838-8041-c88b805e1ec4.png)
Even i added on_train_end hook to it stil it fails.

**Comment by vturrisi** [comment]
I'll take a look tomorrow, but we will migrate to saving after each train epoch. I'm almost sure that the callback is `on_train_epoch_end` and not `on_train_end`, if you wanna check with the former.

**Comment by vturrisi** [comment]
Hey @ankitpatnala I just checked our code and we have already changed this some time ago on: https://github.com/vturrisi/solo-learn/blob/9e725adedc7f28ea44ac4fa2f28c97c2f5bdd853/solo/utils/checkpointer.py#L148-L157
