### ISSUE TITLE
Newly implemented simclr loss function seems to be wrong?

### ISSUE THREAD

**Issue by Hong753** [vturrisi/solo-learn#206]
Correct me if I'm wrong but when using mutiple gpus, the newly implemented simclr loss seems to be wrong.
The problem is in pos_mask.fill_diagonal(False)
As a simple example, for z with shape (N x 2, d) with 2 gpus, the positive mask for the first gpu is correct since the similarities computed are in the shape of (N, N x 2) with the first N dimensions (along dim=1) belonging to view 1, which would be the same as the query view and thus correctly set as False.
However, for gpu 2, the computed similarities would be of shape (N, N x 2) with the last N dimensions(along dim=1) belonging to the same view as the query view. Thus the correct pos_mask would be to set the "second group's diagonals" as False.
Maybe I misunderstood how exaclty the gather function works (from my knowledge, it outputs a list ordered as the rank, thus the gathered outputs for all gpus would be the same order) or some other part of the implementation.

**Comment by vturrisi** [comment]
Indeed the diagonal is wrong and we should set it according to the rank of the device. Already pushed the fix here:
https://github.com/vturrisi/solo-learn/blob/06dd435f220f1b72a035d858c98de7b9ce0327ae/solo/losses/simclr.py#L51-L52
