### ISSUE TITLE
where did the "--strategy" be defined?

### ISSUE THREAD

**Issue by ludysama** [vturrisi/solo-learn#207]
I downloaded the newest codes, and try to train a model using moco, but it reported an error:
`main_pretrain.py: error: unrecognized arguments: --strategy ddp`

I try to find the parser argument named "--strategy", but I didn't find it.  Is it a bug?

**Comment by vturrisi** [comment]
Hey @ludysama you need to update pytorch lightning versions.

**Comment by ludysama** [comment]
Thank you， it works。
