### ISSUE TITLE
how to use more than 1 optimizer and scheduler in the same method?

### ISSUE THREAD

**Issue by ludysama** [vturrisi/solo-learn#213]
I'm trying to write a method that combining moco and rotation prediction. and faced with an problem：all the methods available just uses only 1 optimizer and scheduler. I need 1 cosine scheduler for moco and 1 step scheduler for rotation prediction. 

It seems that now we can only modify the lr and weight_decay for our added model modules, but can't specific a diffirent optimizer and scheduler for it.... right?

**Comment by vturrisi** [comment]
hey @ludysama, to do so, you will need to override this method from base https://github.com/vturrisi/solo-learn/blob/16d021d8053439a3de205337ab2a11d191500b09/solo/methods/base.py#L331 in your new method. Note that we can the property `learnable_parameters` to find the models parameters, but for a quick test, you can just ignore it and manually parse the parameters.

**Comment by ludysama** [comment]
ok, I will try it manually
