### ISSUE TITLE
About num_crops_per_aug argument

### ISSUE THREAD

**Issue by juanigp** [vturrisi/solo-learn#215]
Hi, it is not clear to me how the number of crops and transform pipelines work. 

Under the directory _bash_files/pretrain/imagenet-100/_ some scripts have the argument `--num_crops_per_aug 1 1 ` (for example _byol.sh_), while other have `--num_crops_per_aug 2` (like _simclr.sh_).

Can someone clarify to me why some methods have 2 pipelines but only 1 crop per pipeline, while others have a single pipeline with 2 crops? What would be the difference here?

Thank you in advance!

**Comment by vturrisi** [comment]
Hey @juanigp, SimCLR uses a symmetric augmentation pipeline, i.e. both crops are generated from exactly the same augmentations whereas BYOL (and other works that followed later which borrow from it) use an asymmetric augmentation pipeline (crop 1 has a different random probability for gaussian blur and solarization then crop 2). Our `--num_crops_per_aug` parameter controls how many crops each augmentation pipeline will produce. This adds better flexibility to supporting asymmetric pipelines (line BYOL) and multi-crop (like SWaV). I suggest you check both papers where they detail the augmentations.

**Comment by juanigp** [comment]
Hi @vturrisi thank you for the info, very much appreciated!
