### ISSUE TITLE
is there some implementations based swin?

### ISSUE THREAD

**Issue by liangzimei** [vturrisi/solo-learn#217]
hi, is there some implementations based swin? The Readme says already add swin and vit,  but i find no training parameter configuration or scripts about these ssl methods based swin.

**Comment by DonkeyShot21** [comment]
We rely on `timm`'s implementation of Swin, we just import the constructor function here:
https://github.com/vturrisi/solo-learn/blob/d5b96daec142c0e0a5ca043d787bb4fb9bfef394/solo/utils/backbones.py#L33

**Comment by liangzimei** [comment]
> We rely on `timm`'s implementation of Swin, we just import the constructor function here:
> 
> https://github.com/vturrisi/solo-learn/blob/d5b96daec142c0e0a5ca043d787bb4fb9bfef394/solo/utils/backbones.py#L33

so now there are only net definition  but no training parameter configuration, right？

**Comment by DonkeyShot21** [comment]
You can check `timm`'s code for Swin [here](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/swin_transformer.py). If you need to modify the architecture you can just copy-paste the implementation into `solo-learn` instead of importing.
