### ISSUE TITLE
Some errors occurred after adding ConvNeXt

### ISSUE THREAD

**Issue by yifeiwang77** [vturrisi/solo-learn#226]
1. I still encounter ```ModuleNotFoundError: No module named 'timm.models.convnext'``` after ```pip install timm```
2. When disabling importing convnext, I further encounter ```TypeError: __init__() got an unexpected keyword argument 'img_size'``` after running [the simclr script](https://github.com/vturrisi/solo-learn/blob/main/bash_files/pretrain/cifar/simclr.sh) with ```cifar10```  argument. This ```img_size``` argument seems to be introduced by adding convnext while causing errors with original ones. I fix it by copying ```"resnet" not in args.backbone and```  from Line 254 to Line 199 in ```solo/args/utils.py```.

Environment: Python 3.6 with package versions following ```requirements.txt```.

**Comment by vturrisi** [comment]
Hi. Thanks for letting us know. The issue was an `if` instead of an `elif`, which should now be fixed. About **1**, `convnext` was added very recently to `timm`, so you probably have an outdated package. I suggest just updating it with `pip install timm -U`.
