### ISSUE TITLE
Why does SimCLR use class_loss in training_step?

### ISSUE THREAD

**Issue by ChintanTrivedi** [vturrisi/solo-learn#230]
https://github.com/vturrisi/solo-learn/blob/main/solo/methods/simclr.py#L124

Forgetting why this loss is being added to the nce loss in the training_step, I thought it was only calculated for the validation step or in supcon method.

**Comment by DonkeyShot21** [comment]
Hi! Thanks for using solo-learn. Please, search through the issues before posting. The question has already been answered multiple times:
https://github.com/vturrisi/solo-learn/issues/174
https://github.com/vturrisi/solo-learn/issues/91
https://github.com/vturrisi/solo-learn/issues/128
