### ISSUE TITLE
Is it possible to use different backbone (without sharing parameters) for training SSL ? 

### ISSUE THREAD

**Issue by Vijayraven95** [vturrisi/solo-learn#233]
Amazing repo for SSL. Great work guys! I would like to know where to change so that I can pass the input images to different backbones (like 1 image in Resnet50 and other augmented images in ResNet18). Thank you!

**Comment by Vijayraven95** [comment]
Thanks. And it would be great if you could add VICReg  training with different backbones and without sharing parameters for supporting multi-modal inputs as that would be a great addition to the repo.

**Comment by DonkeyShot21** [comment]
Yes, it would be nice, but it requires a lot of work and I am not sure we can generalize our current design without completely turning the repository upside down
