### ISSUE TITLE
How to evaluate the ResNet18 backbone on object detection? 

### ISSUE THREAD

**Issue by yutaro-s** [vturrisi/solo-learn#266]
Hi.
Thank you for your work! This is a really cool project!

I'm trying to evaluate a trained model whose backbone is ResNet18 on the downstream task.
The program (./downstream/object_detection/train_object_detection.py) assumes that ResNet50 will be used for the backbone.
Could you teach me how to evaluate the ResNet18 backbone on object detection?

**Comment by vturrisi** [comment]
Hey. The code that we have assumes that you want to evaluate a resnet50 and we don't support a resnet18. To chance this, you will need to re-write the model conversion so that it works with a resnet18 and also the detectron code.

**Comment by yutaro-s** [comment]
Thanks for your quick reply. I got it.
