### ISSUE TITLE
The default value for gaussian_prob

### ISSUE THREAD

**Issue by yutaro-s** [vturrisi/solo-learn#297]
The default value for gaussian_prob is 0.5.
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L199
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L272
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L336
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L399

But, the docstrings state 0.0.
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L221
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L293
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L357
https://github.com/vturrisi/solo-learn/blob/main/solo/data/pretrain_dataloader.py#L423

**Comment by vturrisi** [comment]
Thanks for letting us know. There's likely some other inconsistencies with our docstrings/documentations but we need to do a general pass on that and fix all of those together.
