### ISSUE TITLE
Where did you do normalization for supervised contrastive learning?

### ISSUE THREAD

**Issue by NoTody** [vturrisi/solo-learn#307]
Hi, I couldn't find where did you do normalization for supervised contrastive learning implementation. Did you ignore it? In original paper, they did normalization after the projector as this line here https://github.com/HobbitLong/SupContrast/blob/331aab5921c1def3395918c05b214320bef54815/networks/resnet_big.py#L185 .

**Comment by DonkeyShot21** [comment]
In the loss function:
https://github.com/vturrisi/solo-learn/blob/main/solo/losses/simclr.py#L41
