### ISSUE TITLE
About knn evaluation with faiss

### ISSUE THREAD

**Issue by Dongwoo-Im** [vturrisi/solo-learn#314]
Hi, thanks for your release such a nice framework.

I wonder why you did not finish the job of the branch "fix/knn-faiss"

If there's some reason, please let me know. Thanks.

**Comment by DonkeyShot21** [comment]
Hi! Thank you for using solo-learn.

If I remember correctly we found that the advantages of using faiss were not worth it in the end.

**Comment by vturrisi** [comment]
Yeah, I think it was something like @DonkeyShot21 said. However, we would be happy to integrate knn with faiss if you choose to contribute.

**Comment by Dongwoo-Im** [comment]
Thanks for your quick response.

If there's an advantage of using faiss, I'll reopen the issue :]
