### ISSUE TITLE
Barlow Twins ImageNet-1k Checkpoint

### ISSUE THREAD

**Issue by ThomasYerxa** [vturrisi/solo-learn#330]
It seems like there is no actual checkpoint available to download for Barlow Twins pretrained for 100 epochs on ImageNet (the drive folder only contains the args.json folder).

Is it possible to add the actual weights?

**Comment by vturrisi** [comment]
Hey. That's very strange because we had the checkpoint there for sure. Anyway, I'll try to find it and add it as soon as possible.

**Comment by vturrisi** [comment]
@ThomasYerxa sorry about the mega-long delay. Had a lot of issues with vpn/finding the checkpoint. Just re-uploaded it to the google drive folder (you will also be able to download it with the `zoo/imagenet.sh` script.
