### ISSUE TITLE
Finding the Current Epoch

### ISSUE THREAD

**Issue by kkokilep** [vturrisi/solo-learn#333]
Hello,

I am trying to implement a method that makes use of the current epoch to decide when to change a parameter I introduce. However, I am unsure where in the code to extract the current epoch. It seems that this is hidden.

Thanks for any help!

**Comment by DonkeyShot21** [comment]
https://github.com/vturrisi/solo-learn/blob/e38418437698e767c37dabf1f2edae3f04fe6c56/solo/methods/swav.py#L239

**Comment by vturrisi** [comment]
@kkokilep to clarify, `current_epoch` is a pytorch lightning module variable. See https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#current-epoch
