### ISSUE TITLE
How can we use pretrained model for our image classification task?

### ISSUE THREAD

**Issue by saifhassan** [vturrisi/solo-learn#339]
Hey @turian @Froskekongen @Borda @ojss @DonkeyShot21,

Thank you for this nice work. I have one query regarding down-stream task, I have pretrained model on my dataset (image classification) using `main_pretrain.py` with BYOL and simclr and others. Now I want to use this pretrained model for my actual task which is image classification? How can I use that, please guide me regarding this.

Like you have done for `object detection` in sub-repo, I want to perform for image classification.

Thank you in advance.

**Comment by DonkeyShot21** [comment]
You tagged wrong again :)

I replied in the other thread https://github.com/vturrisi/solo-learn/issues/338

**Comment by saifhassan** [comment]
yeah again wrong but I have gone through your profile and github issues/replies. So I knew that you would give response quickly.

Thank you so much.
