### ISSUE TITLE
Error while using `man_umap.py`

### ISSUE THREAD

**Issue by saifhassan** [vturrisi/solo-learn#340]
Hey @vturrisi @DonkeyShot21 

Thank you for nice work.

While running `main_umap.py` with pretrained model using BYOL method, it gives following error:

**Command**
```
python main_umap.py --pretrained_checkpoint_dir trained_models/old/byol/custom/ --batch_size=16 --num_workers 2 --dataset custom --train_data_path ./datasets/custom/train --val_data_path ./datasets/custom/val
```

**Error**
```
Traceback (most recent call last):
  File "main_umap.py", line 72, in <module>
    main()
  File "main_umap.py", line 45, in main
    .load_from_checkpoint(ckpt_path, strict=False, **method_args)
  File "/home/user1/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
TypeError: _load_model_state() got multiple values for argument 'checkpoint'
```

Please guide.

**Comment by vturrisi** [comment]
@saifhassan please don't tag everyone when posting new issues. The main contributors are myself and @DonkeyShot21 and we always try to address issues as soon as possible. Which files do you have inside this folder? `main_umap.py` expects a folder in the same structure as the checkpoints that we save during training, so a checkpoint file and an args file. It looks like you have more than one checkpoint file.

**Comment by saifhassan** [comment]
> @saifhassan please don't tag everyone when posting new issues. The main contributors are myself and @DonkeyShot21 and we always try to address issues as soon as possible. Which files do you have inside this folder? `main_umap.py` expects a folder in the same structure as the checkpoints that we save during training, so a checkpoint file and an args file. It looks like you have more than one checkpoint file.

sorry for tagging everyone, updated tagged persons. Yeah, I got it regarding umap. I will let you know if any more queries.

Thanks

**Comment by saifhassan** [comment]
> @saifhassan please don't tag everyone when posting new issues. The main contributors are myself and @DonkeyShot21 and we always try to address issues as soon as possible. Which files do you have inside this folder? `main_umap.py` expects a folder in the same structure as the checkpoints that we save during training, so a checkpoint file and an args file. It looks like you have more than one checkpoint file.

I am running `umap.sh` file which contains command as follows:

```
python3 main_umap.py \
    --dataset custom \
    --train_data_path ./datasets/raf-db/train \
    --val_data_path ./datasets/raf-db/val \
    --batch_size 16 \
    --num_workers 10 \
    --pretrained_checkpoint_dir ./trained_models/byol/zu2661zo
```

and `./trained_models/byol/zu2661zo` directory contains `.json` and `.ckpt` files. that's all.

Still same error.

**Comment by vturrisi** [comment]
How many files do you have in that folder?

**Comment by saifhassan** [comment]
> How many files do you have in that folder?

just two files one `.json` and one `.ckpt`

**Comment by saifhassan** [comment]
only the files generated by `main_pretrain.py` (one ckpt and one json).

**Comment by 2hindas** [comment]
I am trying to use KNN evaluation, and the exact same error shows up. In my case, I also only have a folder containing just a checkpoint file and an args.json file.

**Comment by davidrzs** [comment]
Exactly the same issue. Tried to debug, but I am somewhat stuck why this would suddenly appear.

**Comment by vturrisi** [comment]
I'll take a look at it in the next few days. Thanks for reporting.

**Comment by vturrisi** [comment]
#344 will fix this issue.
