### ISSUE TITLE
Classification Loss

### ISSUE THREAD

**Issue by mammadov7** [vturrisi/solo-learn#353]
Dear Authors,

Hope you are doing well.

In all of the pretraining methods. For example, there is a class_loss in SimCLR that doesn't exist in the original implementation. Could you please tell the reason why you have added class loss?
 
Best regards,

**Comment by vturrisi** [comment]
Hey, this has been asked many times. I think at this point it's even worth to add it to the readme. 

That loss is used only to train a linear classifier together with the backbone model. We detach the features before giving them to the classifier, so the classification loss only acts on the linear classifier. This can be seen as an "online linear classifier". In our experiments, we saw that this performs very similarly to the offline linear classifier.
