### ISSUE TITLE
Custom Dataset object detection

### ISSUE THREAD

**Issue by kalikhademi** [vturrisi/solo-learn#355]
Hi, 

I have pretrained a SSL method using main_pretrain.py script. I obtained the checkpoint and I would like to use it to detect objects on my custom dataset. Could you please let me know how to register my custom dataset to work with train_object_detection.py. My dataset has coco format json files for both train and valid.

**Comment by vturrisi** [comment]
Hey @kalikhademi. The object detection code is taken from the original MoCo GitHub and slightly adapted. It relies heavily on detectron as well, so I suggest you to check detectron directly.
