### ISSUE TITLE
Train/Test Split for Pretraining via imagenet

### ISSUE THREAD

**Issue by LightingMc** [vturrisi/solo-learn#361]
What is the train-test split used for the pre-training on ImageNet? Do you have a file that describes which image goes where? What is the split percentage?

**Comment by vturrisi** [comment]
It's the default train/val splits for imagenet.

**Comment by vturrisi** [comment]
It already comes divided into train and val. You can download it from multiple sources, e.g. https://huggingface.co/datasets/imagenet-1k/tree/main
