### ISSUE TITLE
Are all the weights available from 16-bit precision? Not 16-mixed?

### ISSUE THREAD

**Issue by LightingMc** [vturrisi/solo-learn#367]
User warning: 16 is supported for historical reasons, but its usage is discouraged. Please set your precision to 16-mixed instead!

**Comment by vturrisi** [comment]
Most models and scripts are pretty old, so they were executed when 16-mixed was not supported in lightning. I'll eventually update all scripts and the imports for lightning, but the models will be kept at the current precision.
