### ISSUE TITLE
Imagenet results reported from Linear Eval or Fine tuning?

### ISSUE THREAD

**Issue by LightingMc** [vturrisi/solo-learn#372]
![image](https://github.com/vturrisi/solo-learn/assets/42900802/42150c1b-87b3-4a89-aa19-c94f59a933f7)

**Comment by vturrisi** [comment]
Only MAE was finetuned.

**Comment by LightingMc** [comment]
What is the LR rate that you used for the linear Eval? I thought it was supposed to be a fixed LR of 0.1. But the scripts in the repo say otherwise. I am having a hard time reproducing the results at a fixed LR of 0.1

**Comment by vturrisi** [comment]
It depends on the method. We used the setting in our config files.
