### ISSUE TITLE
after reading your document, i have no idea how to use VIbCReg in solo-learn to train custom dataset， can you show me an example?

### ISSUE THREAD

**Issue by RuojiWang** [vturrisi/solo-learn#386]
after reading your document, i have no idea how to use VIbCReg in solo-learn to train custom dataset， can you show me an example?

**Comment by vturrisi** [comment]
Hey. You should replace the `data` part in: https://github.com/vturrisi/solo-learn/blob/b69b4bd27472593919956d9ac58902a301537a4d/scripts/pretrain/imagenet-100/vibcreg.yaml#L1-L56 

with: https://github.com/vturrisi/solo-learn/blob/b69b4bd27472593919956d9ac58902a301537a4d/scripts/pretrain/custom/byol.yaml#L28-L37
