### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by aliechoes** [vturrisi/solo-learn#56]
Hi

Is there any tutorial for this repo that one can use?

Thanks a lot :)

**Comment by DonkeyShot21** [comment]
Hi! Thanks for your interest in our repository.

We are working very hard to release a stable version of solo-learn in a few days. We will definitely add some explanation on how to use and extend the repo. For now, you can find all the instructions for installation in the readme and the commands in the `bash_files` folder. 

What kind of tutorials would you be more interested in? How to use? How to extend? Code structure documentation?

**Comment by aliechoes** [comment]
thanks for the response. So I would prefer to have tutorials on training on my own data

**Comment by vturrisi** [comment]
Hey,

For now, you can probably try to work your way around following `main_contrastive.py` and `solo/utils/contrastive_dataloader.py`. 
If you have custom data, one thing what you probably try is:

1- Create a transforms pipeline following those on `contrastive_dataloader.py`
2- Pass it to `prepare_n_crop_transform` with n_crops=2
3- And do something like this `train_dataset = dataset_with_index(ImageFolder)(train_dir, transform)` 

At this point, you will have a working `Dataset` that already has the transformation pipelines needed to produce two different augmentations of each image. You just need to convert it to a `Dataloader`, and I think you are done.

There might be some issues in the way, so if you have any questions feel free to let us know.

We will try to support this in an easier way for the future.

**Comment by DonkeyShot21** [comment]
Support for custom datasets has been added in #103
